### PR TITLE
fix: support capturing SIGTERM signal to shutdown gracefully

### PR DESCRIPTION
**Pull request by stanxing**
https://github.com/hipages/php-fpm_exporter/issues/81

### CODE REVIEW

**Comment by estahn** [comment]
@stanxing Thanks for your contribution. Did you test this? I would have expected to see the shutdown message (https://github.com/hipages/php-fpm_exporter/blob/master/cmd/server.go#L115).

I tested this on MacOS.

**Comment by estahn** [comment]
> @stanxing Thanks for your contribution. Did you test this? I would have expected to see the shutdown message (https://github.com/hipages/php-fpm_exporter/blob/master/cmd/server.go#L115).
> 
> I tested this on MacOS.

Ok, never mind. I killed `go run` instead of the actual process. Looks good 👍

**Comment by stanxing** [comment]
> Ok, never mind. I killed go run instead of the actual process. 

Tested on Ubuntu 18.04 with golang 1.13.4
 
Screenshot from 2020-03-21 11-00-24

**Comment by stanxing** [comment]
> Ok, never mind. I killed go run instead of the actual process. 

Tested on Ubuntu 18.04 with golang 1.13.4
 
Screenshot from 2020-03-21 11-00-24

**Comment by estahn** [comment]
@all-contributors please add stanxing for code

**Pull request merged**
