### PR TITLE
Bump Alpine version to 3.13

### PR DESCRIPTION
**Pull request by danielocallaghan**
This upgrade introduces the following updates to Alpine including fixes to several CVEs

https://alpinelinux.org/posts/Alpine-3.13.2-released.html

Related issue:
https://github.com/hipages/php-fpm_exporter/issues/136

### CODE REVIEW

**Review by Wenliang-CHEN — APPROVED** [review]
lgtm

**Review by Wenliang-CHEN — APPROVED** [review]

**Comment by danielocallaghan** [comment]
Hi @Wenliang-CHEN, thank you for your review, do you know how I can fix this currently failing ci check?
Looks like this is a blocker:
https://github.com/hipages/php-fpm_exporter/pull/135/checks?check_run_id=2020575062

**Comment by Wenliang-CHEN** [comment]
@danielocallaghan sorry I mistaken this to be the Personio repo.  Probably this needs some attention from the maintainer. I am unapproving for now.

**Comment by estahn** [comment]
@all-contributors please add @danielocallaghan for code

**Pull request merged**
