### PR TITLE
#19 fix connect to unix sock file issue

### PR DESCRIPTION
**Pull request by herb123456**
#19 
uri.Hostname() and uri.Port() is empty when address is a unix socket path.

So I add a condition to decide where the address is.

### CODE REVIEW

**Comment by herb123456** [comment]
looks like this function have too many if condition.

I will refactor this function.

**Comment by herb123456** [comment]
already pass codeclimate test

**Comment by herb123456** [comment]
@estahn 

I can not resolve the circleci issue.

```
Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
Usage:
  cc-test-reporter after-build [flags]

Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier
      --insecure                     send coverage insecurely (without HTTPS)
  -p, --prefix string                the root directory where the coverage analysis was performed (default "/go/src/github.com/hipages/php-fpm_exporter")

Global Flags:
  -d, --debug   run in debug mode

Exited with code 255
```

It looks like ./cc-test-reporter error, but I don't know how to fix it.

Please help me.

**Comment by estahn** [comment]
@herb123456 I have fixed the issue with CircleCI. 

First of all thanks for your implementation. It helped me think through a couple of things. The reason why I adjusted your solution are:

* `p.connect` – The concern for this method doesn't feel clearly defined to me, especially with the return of `*FCGIClient` and `statusPath`.
* `defer fcgi.Close()` is detached from `fcgiclient.DialTimeout(...)`
* `p.connect` should have a counterpart `p.disconnect`

I do like the idea of `p.connect` and `p.disconnect` for mocking purposes.

Please have a look at #23 and let me know your thoughts.

**Pull request closed without merging**
