### PR TITLE
feat: add scrape_url as prometheus label for each metric

### LINKED ISSUE #53: adding more pools getting 500 error
Hi,

i have added two pools using server command and i get 500 error.
**`server returned error: HTTP/1.1 500 Internal Server Error`**

command: 
```
php-fpm_exporter server --phpfpm.scrape-uri tcp://10.100.63.316:9002/upstream-php71-status,tcp://10.100.124.49:9002/upstream-php71-status
```

Note adding 1 pool works fine.

### PR DESCRIPTION
**Pull request by sas1024**
Fix #53 issue

### CODE REVIEW

**Comment by estahn** [comment]
@sas1024 Thanks for your PR. I will get the CI pipeline fixed today.

**Comment by estahn** [comment]
@sas1024 Can you please update with the latest master?

**Comment by sas1024** [comment]
> @sas1024 Can you please update with the latest master?

Sure. Done.

**Comment by sas1024** [comment]
@estahn it's seems that CI pipeline need more fixes.

**Comment by estahn** [comment]
> @estahn it's seems that CI pipeline need more fixes.

I have migrated this to GitHub Actions and removed CircleCI.

In regards to the PR I'm wondering if this should be optional. We're running `php-fpm_exporter` currently as side-care and this wouldn't have any benefit.

Thoughts?

**Comment by estahn** [comment]
@all-contributors please add sas1024 for code

**Pull request merged**
